---
title: "Writing"
output: 
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
    theme: cosmo
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(kableExtra)
```

**Tips**  
* Be concrete rather than abstract
* Use active verbs (exciting and not passive voice)
* Eliminate forms of “to be” as much as possible (e.g. “be” “is”, “was”, “were”, “are”)
* Put human beings in rather than writing impersonally
* Use shorter sentences
* Use simpler and more compact words
* Omit needless words
* Include a conclusion
(above advice from https://www.jamesgmartin.center/2013/05/teaching-college-students-to-write/)

Write a specific [thesis statement](http://www.cws.illinois.edu/workshop/writers/tips/thesis/)

The [Hemingway App](http://www.hemingwayapp.com/) will correct grammar and writing errors. Use it!

[Grammarly](https://www.grammarly.com/) corrects a variety of errors. Use it!

Learning to write: During the first week of class we will discuss the expectations for writing in this course, including the grading rubric. For initial papers key points to address will be noted to aid in learning what is important to include in a paper. Throughout the course we will also discuss how assigned readings approach constructing well reasoned arguments. Because there are many assignments throughout the semester there is significant opportunity to improve based on critique from both the professor and students in the course.

This course will require engagement with material, critical thinking, and the ability to write well-constructed arguments. The Academic Enhancement Center helps URI students succeed through three services: Academic Coaching, Subject-Based Tutoring, and The Writing Center. To learn more about any of these services, please visit uri.edu/aec or call 401-874-2367 to speak with reception staff. Hours are posted at http://web.uri.edu/ceps/academic-skills-center/